name: Broadcast-for-PAF
version: ${project.version}
author: Simonsator
depend: [PartyAndFriendsGUI]
main: de.simonsator.partyandfriends.broadcast.gui.BroadcastSettingPlugin
description: An add-on for party and friends to add /friend broadcast
api-version: 1.13